FROM riobueno/php-apache:8.3

ARG WORDPRESS_VERSION
ENV WORDPRESS_VERSION=${WORDPRESS_VERSION}

RUN set -ex; \
    curl -o wordpress.tar.gz -fSL "https://wordpress.org/wordpress-${WORDPRESS_VERSION}.tar.gz"; \
    tar -xzf wordpress.tar.gz -C /usr/src/; \
    rm wordpress.tar.gz;

RUN mv /usr/src/wordpress/* /var/www/html/; \
    rm -rf /var/www/html/wp-content/themes/tw*

COPY extra/* /var/www/html/

RUN chown -R www-data:www-data /var/www/html/
