FROM riobueno/php:7.4-apache

ENV WORDPRESS_VERSION 5.6
ENV WORDPRESS_SHA1 db8b75bfc9de27490434b365c12fd805ca6784ce

RUN set -ex; \
	curl -o wordpress.tar.gz -fSL "https://wordpress.org/wordpress-${WORDPRESS_VERSION}.tar.gz"; \
	echo "$WORDPRESS_SHA1 *wordpress.tar.gz" | sha1sum -c -; \
    tar -xzf wordpress.tar.gz -C /usr/src/; \
    rm wordpress.tar.gz; 

RUN mv /usr/src/wordpress/* /var/www/html/; \
    rm -rf /var/www/html/wp-content/themes/tw*

COPY extra/* /var/www/html/

RUN	chown -R www-data:www-data /var/www/html/

    

# ENTRYPOINT ["docker-entrypoint.sh"]
# CMD ["apache2-foreground"]
