FROM riobueno/php-apache:7.4

ENV WORDPRESS_VERSION 5.8.2

RUN set -ex; \
	curl -o wordpress.tar.gz -fSL "https://wordpress.org/wordpress-${WORDPRESS_VERSION}.tar.gz"; \
    tar -xzf wordpress.tar.gz -C /usr/src/; \
    rm wordpress.tar.gz; 

RUN mv /usr/src/wordpress/* /var/www/html/; \
    rm -rf /var/www/html/wp-content/themes/tw*

COPY extra/* /var/www/html/

RUN	chown -R www-data:www-data /var/www/html/

# CMD ["apache2-foreground"]
